// Mock of a functional API client generated by Orval, Kubb, or OpenAPI-TS
// Standalone exported functions without a class wrapper

export async function getUser(id: string): Promise<{ id: string; name: string }> {
    return { id, name: `User_${id}` };
}

export async function listUsers(limit?: number): Promise<{ id: string; name: string }[]> {
    const count = limit ?? 2;
    const users: { id: string; name: string }[] = [];
    for (let i = 1; i <= count; i++) {
        users.push({ id: `${i}`, name: `User_${i}` });
    }
    return users;
}

export async function deleteUser(id: string): Promise<boolean> {
    return id.length > 0;
}

